"""project init migrations

Revision ID: 2ddb158d4480
Revises:
Create Date: 2026-01-06 18:08:56.544832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ddb158d4480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='uq_cafes_name_address')
    )
    op.create_table('dish',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_dishes_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outboxmessage',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ENQUEUED', 'SENT', 'FAILED', 'CANCELED', name='outbox_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_aggregate_type_id', 'outboxmessage', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_outbox_status_available_at', 'outboxmessage', ['status', 'available_at'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tg_id', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='ck_user_email_or_phone'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('booking',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('guest_number', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('BOOKING', 'ACTIVE', 'CANCELED', name='booking_status'), server_default=sa.text("'BOOKING'"), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('guest_number > 0', name='ck_booking_guest_number_positive'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_cafe_id'), 'booking', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    op.create_index('ix_bookings_cafe_date', 'booking', ['cafe_id', 'booking_date'], unique=False)
    op.create_index('ix_bookings_cafe_date_status', 'booking', ['cafe_id', 'booking_date', 'status'], unique=False)
    op.create_index('ix_bookings_user_date', 'booking', ['user_id', 'booking_date'], unique=False)
    op.create_table('cafemanagerlink',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafemanagerlink_cafe_id'), 'cafemanagerlink', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_cafemanagerlink_user_id'), 'cafemanagerlink', ['user_id'], unique=False)
    op.create_index('uq_cafe_managers_active', 'cafemanagerlink', ['cafe_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active IS TRUE'))
    op.create_table('dishcafelink',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'cafe_id', name='uq_dish_cafe')
    )
    op.create_index(op.f('ix_dishcafelink_cafe_id'), 'dishcafelink', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_dishcafelink_dish_id'), 'dishcafelink', ['dish_id'], unique=False)
    op.create_table('slot',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_slots_end_time_gt_start_time'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('seat_number BETWEEN 1 AND 12', name='check_seat_number_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_cafe_id'), 'table', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_table_seat_number'), 'table', ['seat_number'], unique=False)
    op.create_table('usersession',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_expires_at', 'usersession', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'usersession', ['user_id'], unique=False)
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.create_table('bookingtableslot',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'table_id', 'slot_id', name='uq_booking_table_slot')
    )
    op.create_index(op.f('ix_bookingtableslot_booking_id'), 'bookingtableslot', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookingtableslot_slot_id'), 'bookingtableslot', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookingtableslot_table_id'), 'bookingtableslot', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookingtableslot_table_id'), table_name='bookingtableslot')
    op.drop_index(op.f('ix_bookingtableslot_slot_id'), table_name='bookingtableslot')
    op.drop_index(op.f('ix_bookingtableslot_booking_id'), table_name='bookingtableslot')
    op.drop_table('bookingtableslot')
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_index('ix_user_sessions_user_id', table_name='usersession')
    op.drop_index('ix_user_sessions_expires_at', table_name='usersession')
    op.drop_table('usersession')
    op.drop_index(op.f('ix_table_seat_number'), table_name='table')
    op.drop_index(op.f('ix_table_cafe_id'), table_name='table')
    op.drop_table('table')
    op.drop_table('slot')
    op.drop_index(op.f('ix_dishcafelink_dish_id'), table_name='dishcafelink')
    op.drop_index(op.f('ix_dishcafelink_cafe_id'), table_name='dishcafelink')
    op.drop_table('dishcafelink')
    op.drop_index('uq_cafe_managers_active', table_name='cafemanagerlink', postgresql_where=sa.text('is_active IS TRUE'))
    op.drop_index(op.f('ix_cafemanagerlink_user_id'), table_name='cafemanagerlink')
    op.drop_index(op.f('ix_cafemanagerlink_cafe_id'), table_name='cafemanagerlink')
    op.drop_table('cafemanagerlink')
    op.drop_index('ix_bookings_user_date', table_name='booking')
    op.drop_index('ix_bookings_cafe_date_status', table_name='booking')
    op.drop_index('ix_bookings_cafe_date', table_name='booking')
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_cafe_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_outbox_status_available_at', table_name='outboxmessage')
    op.drop_index('ix_outbox_aggregate_type_id', table_name='outboxmessage')
    op.drop_table('outboxmessage')
    op.drop_table('image')
    op.drop_table('dish')
    op.drop_table('cafe')
    # ### end Alembic commands ###
