"""create session table

Revision ID: 9fddfdb4f1e4
Revises: 2c21000cbe41
Create Date: 2025-12-30 20:25:55.614143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fddfdb4f1e4'
down_revision: Union[str, Sequence[str], None] = '2c21000cbe41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('usersession',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_active', 'usersession', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_active', table_name='usersession')
    op.drop_table('usersession')
    # ### end Alembic commands ###
