# Роли пользователя
ROLE_USER = 0
ROLE_MANAGER = 1
ROLE_ADMIN = 2

# Телефон
PHONE_MAX_LENGTH = 20

# Описание
DESCRIPTION_MAX_LENGTH = 400
DESCRIPTION_MIN_LENGTH = 10

# Кафе
CAFE_NAME_MAX_LENGTH = 100
CAFE_NAME_MIN_LENGTH = 1
CAFE_ADDRESS_MAX_LENGTH = 200

# UUID в строковом виде
UUID_LENGTH = 36

# Столы
TABLE_DESCRIPTION_MAX_LENGTH = 256
TABLE_MIN_SEATS_NUMBER = 1
TABLE_MAX_SEATS_NUMBER = 12
